### ISSUE TITLE
Getting logged out and Settings resetting 

### ISSUE THREAD

**Issue by meteorsquare** [jakubito/spotify-release-list#27] opened 2021-11-11 14:12 UTC
I am logged out after opening the browser and need to log in again. The filters and other settings also resetto default so I have to see again a bunch of (garbage, "unofficial" third party) compilation releases that some artists I follow appear on.

I was using Brave Browser.

<img width="1381" alt="Screenshot 2021-11-11 at 22 13 12" src="https://user-images.githubusercontent.com/58662679/141312842-6f12f3a2-0e13-43a6-8120-76d1ca87f40e.png">

**Comment by jakubito** [comment] 2021-12-14 09:45
I've had multiple users reporting problems with the Brave browser. I'm not sure what the problem is, but I assume it has something to do with the browser preventing the app from saving data locally (probably some kind of data size cap). Unfortunately, I don't have time to look into this right now, sorry.

**Comment by jakubito** [comment] 2022-02-08 06:59
I'm closing this one. I can't support every browser that decides to block basic browser features, such as localStorage/IndexedDB. Maybe there is a way to add an exception within Brave to allow saving data locally? I don't really know. If that's not possible, please use any other modern browser to use this app.

**Closed as completed by jakubito** 2022-02-08 06:59 UTC
